---
name: ES Lint

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test-eslint:
        name: Test ES Lint Config
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x, 24.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: eslint/package-lock.json
            - run: npm ci
              working-directory: ./eslint
            - run: npm run build --if-present
              working-directory: ./eslint
            - run: npm test
              working-directory: ./eslint

    publish-eslint:
        name: Publish ES Lint Config
        needs: test-eslint
        if: github.event_name == 'push' && github.ref_name == 'main'  # This condition limits the job to pushes to the main branch
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                node-version: 20
            - run: npm ci
              working-directory: ./eslint
            - id: publish
              uses: JS-DevTools/npm-publish@v4
              with:
                package: ./eslint
                token: ${{ secrets.GH_STYLE_NPM_TOKEN }}
            - if: ${{ steps.publish.outputs.type }}
              run: |
                echo "Version changed! Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.id  }}"
