---
name: ES Lint

on:
    push:
        branches: ["**"]  # Run on all branches
    pull_request:
        branches: ["**"]  # Run on PRs to any branch

jobs:
    test-eslint:
        name: Test ES Lint Config
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x, 24.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: eslint/package-lock.json
            - run: npm ci
              working-directory: ./eslint
            - run: npm run build --if-present
              working-directory: ./eslint
            - run: npm test
              working-directory: ./eslint

    security-scan:
        name: Security Scan
        runs-on: ubuntu-latest
        permissions:
            security-events: write
            contents: read
            actions: read

        steps:
            - uses: actions/checkout@v5
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript-typescript
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3

    dependency-check:
        name: Dependency Vulnerability Check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js 20.x
              uses: actions/setup-node@v5
              with:
                  node-version: 20.x
                  cache: "npm"
                  cache-dependency-path: eslint/package-lock.json
            - run: npm ci
              working-directory: ./eslint
            - name: Run npm audit
              run: npm audit --audit-level=high
              working-directory: ./eslint

    publish-eslint:
        name: Publish ES Lint Config
        needs: [test-eslint, security-scan, dependency-check]
        if: github.event_name == 'push' && github.ref_name == 'main'  # This condition limits the job to pushes to the main branch
        runs-on: ubuntu-latest
        permissions:
            id-token: write  # Required for OIDC
            contents: read   # Required to checkout the repo

        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                node-version: 20
                registry-url: 'https://registry.npmjs.org'
            - name: Update npm
              run: npm install -g npm@latest
            - run: npm ci
              working-directory: ./eslint
            - name: Get package version
              id: package-version
              run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
              working-directory: ./eslint
            - name: Check if version exists on NPM
              id: version-check
              run: |
                if npm view eslint-config-shaunburdick@${{ steps.package-version.outputs.version }} version 2>/dev/null; then
                  echo "exists=true" >> $GITHUB_OUTPUT
                else
                  echo "exists=false" >> $GITHUB_OUTPUT
                fi
              working-directory: ./eslint
            - name: Publish to NPM
              if: steps.version-check.outputs.exists == 'false'
              run: |
                if [[ "${{ steps.package-version.outputs.version }}" == *"beta"* ]]; then
                  npm publish --tag beta --provenance --access public
                else
                  npm publish --provenance --access public
                fi
              working-directory: ./eslint
            - name: Publish status
              if: steps.version-check.outputs.exists == 'false'
              run: |
                echo "Published version ${{ steps.package-version.outputs.version }} to NPM"
